development:  
  adapter: postgresql
  encoding: unicode
  database: mmagap
  pool: 5
  port: 5432
  host: localhost
  username: postgres
  password: postgres
  

test:
  adapter: postgresql
  encoding: unicode
  database: da51u9726vjstr
  pool: 5
  port: 5432
  host: ec2-107-22-190-179.compute-1.amazonaws.com
  username: bilyhptmhsmtqd
  password: D_xeNSIskUSq-eOKNt7rKOMd7N

production:
  adapter: postgresql
  encoding: unicode
  database: da51u9726vjstr
  pool: 5
  port: 5432
  host: ec2-107-22-190-179.compute-1.amazonaws.com
  username: bilyhptmhsmtqd
  password: D_xeNSIskUSq-eOKNt7rKOMd7N
